language: ruby
rvm:
  - 2.1.5
  - 2.0.0
  - 1.9.3
env:
  - PUPPET_VERSION=3.4.3
  - PUPPET_VERSION=3.6.2
  - PUPPET_VERSION=3.7.3
notifications:
  webhooks:
    urls:
      - http://travis-notify.mayflower.de/opensource
    on_start: true
