language: ruby
rvm:
  - 2.1.5
  - 2.0.0
  - 1.9.3
  - 1.8.7
env:
  - PUPPET_VERSION=3.4.3
  - PUPPET_VERSION=3.6.2
  - PUPPET_VERSION=3.7.3
notifications:
  webhooks:
    urls:
      - http://hubert.mayflower.de/hubot/travisci/devops
    on_start: true
